#ifndef TOKENS_H_INCLUDED
#define TOKENS_H_INCLUDED

enum TOKEN_TYPE {
    TK_TYPE_RESERVED_WORD, 
    TK_TYPE_SPECIAL_CHAR, 
    TK_TYPE_OPERATOR, 
    TK_TYPE_ID, 
    TK_TYPE_LITERAL 
}TOKEN_TYPES;

enum VAR_TYPE{
    TYPE_INT,
    TYPE_FLOAT,
    TYPE_BOOL,
    TYPE_CHAR,
    TYPE_STRING
    
}VAR_TYPES;



#endif // TOKENS_H_INCLUDED
